drops:
  COBBLESTONE: GOLD_INGOT
  IRON_ORE: IRON_INGOT
  DIAMOND_ORE: DIAMOND
  
worlds:
  - world
  - world_nether
  
messages:
  reload: "&5TDropInventory &e> &aConfiguration reloaded."
  no-permission: "&5TDropInventory &e> &cYou don't have permission to use this command."
  version: "&5TDropInventory &e> &aPlugin version: %version%"

  